services:
#    kit_paginator.example:
#        class: Kit\PaginatorBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
    kit_paginator.paginator:
        class: Kit\PaginatorBundle\Service\PaginatorService
        arguments: ["@doctrine.dbal.default_connection", "@request_stack"]
    twig.extension.pagination_extension:
        class: Kit\PaginatorBundle\Twig\PaginationExtension
        tags:
            - { name: twig.extension }